name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Install Taskfile
        run: go install github.com/go-task/task/v3/cmd/task@latest
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Update version info
        run: |
          git_commit=$(git rev-parse --short HEAD)
          build_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "Setting version to $VERSION, commit $git_commit, build date $build_date"
          sed -i "s/Version = \".*\"/Version = \"$VERSION\"/g" pkg/version/version.go
          sed -i "s/GitCommit = \".*\"/GitCommit = \"$git_commit\"/g" pkg/version/version.go
          sed -i "s/BuildDate = \".*\"/BuildDate = \"$build_date\"/g" pkg/version/version.go
          cat pkg/version/version.go
      
      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "CMD directory structure:"
          ls -la cmd/
          echo "CMD/kube-ai directory structure:"
          ls -la cmd/kube-ai/

      - name: Build binaries manually
        run: |
          mkdir -p ./bin
          echo "Building manually instead of using task..."
          # Linux
          GOOS=linux GOARCH=amd64 go build -ldflags "-X kube-ai/pkg/version.Version=$VERSION -X kube-ai/pkg/version.GitCommit=$(git rev-parse --short HEAD) -X kube-ai/pkg/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ) -s -w" -o ./bin/kube-ai-linux-amd64 ./cmd/kube-ai
          GOOS=linux GOARCH=arm64 go build -ldflags "-X kube-ai/pkg/version.Version=$VERSION -X kube-ai/pkg/version.GitCommit=$(git rev-parse --short HEAD) -X kube-ai/pkg/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ) -s -w" -o ./bin/kube-ai-linux-arm64 ./cmd/kube-ai
          # MacOS
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X kube-ai/pkg/version.Version=$VERSION -X kube-ai/pkg/version.GitCommit=$(git rev-parse --short HEAD) -X kube-ai/pkg/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ) -s -w" -o ./bin/kube-ai-darwin-amd64 ./cmd/kube-ai
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X kube-ai/pkg/version.Version=$VERSION -X kube-ai/pkg/version.GitCommit=$(git rev-parse --short HEAD) -X kube-ai/pkg/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ) -s -w" -o ./bin/kube-ai-darwin-arm64 ./cmd/kube-ai
          # Windows
          GOOS=windows GOARCH=amd64 go build -ldflags "-X kube-ai/pkg/version.Version=$VERSION -X kube-ai/pkg/version.GitCommit=$(git rev-parse --short HEAD) -X kube-ai/pkg/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ) -s -w" -o ./bin/kube-ai-windows-amd64.exe ./cmd/kube-ai
          # Create checksums
          cd ./bin && sha256sum kube-ai-* > checksums.txt
      
      - name: Extract release notes from CHANGELOG
        id: extract_notes
        run: |
          CHANGELOG_CONTENT=$(./scripts/auto-release.sh $VERSION extract-notes)
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Kube-AI v${{ env.VERSION }}
          files: |
            bin/*
          draft: false
          prerelease: false
          generate_release_notes: false
          body: |
            # Kube-AI ${{ env.VERSION }}
            
            ${{ env.CHANGELOG_CONTENT }}
            
            ## Installation
            
            ### Linux (amd64)
            ```bash
            curl -L https://github.com/dalekurt/kube-ai/releases/download/v${{ env.VERSION }}/kube-ai-linux-amd64 -o kube-ai
            chmod +x kube-ai
            sudo mv kube-ai /usr/local/bin/
            ```
            
            ### macOS (Apple Silicon)
            ```bash
            curl -L https://github.com/dalekurt/kube-ai/releases/download/v${{ env.VERSION }}/kube-ai-darwin-arm64 -o kube-ai
            chmod +x kube-ai
            sudo mv kube-ai /usr/local/bin/
            ```
            
            See the [documentation](README.md) for more details. 